skip-check:
  - CKV_TF_1
  - CKV_TF_2
  - CKV_AWS_18
  - CKV2_AWS_61
  - CKV2_AWS_62
  - CKV_AWS_115
  - CKV_AWS_116
  - CKV_AWS_117
  - CKV_AWS_124
  - CKV_AWS_144
  - CKV_AWS_145
  - CKV_AWS_173
  - CKV_AWS_195
  - CKV_AWS_300
