name: Validate

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# Permissions setup for pre-commit, according to ADR-EAO07
permissions:
  contents: read # Required to checkout the code, but can’t write
  id-token: none # Explicitly prevent OIDC token generation (‘none’ is the default)
  packages: none # Explicitly prevent package access (‘none’ is the default)
  # Other permissions take the value 'none' by default

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install terraform and dependencies
      uses: alphagov/gds-tech-and-security-github-actions/terraform/deps@4b0a3ad58c1ea4b3ff1d5ed0a5ae6bc1c91455ec # v0.1.22
      with:
        trivy-version: v0.69.3

    - name: Run pre-commit
      uses: alphagov/gds-tech-and-security-github-actions/pre-commit@4b0a3ad58c1ea4b3ff1d5ed0a5ae6bc1c91455ec # v0.1.22
