name: Validate

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# Permissions setup for pre-commit, according to ADR-EAO07
permissions:
  contents: read # Required to checkout the code, but can’t write
  id-token: none # Explicitly prevent OIDC token generation (‘none’ is the default)
  packages: none # Explicitly prevent package access (‘none’ is the default)
  # Other permissions take the value 'none' by default

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install terraform and dependencies
      uses: alphagov/gds-tech-and-security-github-actions/terraform/deps@47ffdc3007aef6b4857115b97135ed8b7b7c18ca # v0.1.7
      with:
        trivy-version: v0.69.3

    - name: Run pre-commit
      uses: alphagov/gds-tech-and-security-github-actions/pre-commit@0887a2b5712cf4e192ca4340f7c494606672a6bf # v0.1.6
