name: Validate

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# Permissions setup for pre-commit, according to ADR-EAO07
permissions:
  contents: read # Required to checkout the code, but can’t write
  id-token: none # Explicitly prevent OIDC token generation (‘none’ is the default)
  packages: none # Explicitly prevent package access (‘none’ is the default)
  # Other permissions take the value 'none' by default

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Install terraform and dependencies
      uses: alphagov/gds-github-workflows/terraform/deps@7b4a3ee296ab78c4cfa5aec390d6c5a989d7c601 # v0.1.10
      with:
        trivy-version: v0.69.3

    - name: Run pre-commit
      uses: alphagov/gds-github-workflows/pre-commit@7b4a3ee296ab78c4cfa5aec390d6c5a989d7c601 # v0.1.10
